import XCTest
@testable import AoC2023

final class D11Tests: XCTestCase {
    let input1 = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""
    func testExample() throws {
        let adventDay = Day11(input: input1)
        XCTAssertEqual(adventDay.partOne(), 374)
    }
    
}
